# Site/SEO settings
email: admin@btor.fr
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Thibaut BAYER
title: btor.fr
description: >
  Passionné d'informatique, de développement web & applicatif depuis plus de 10 ans. Je partage mon quotidien de tech !
url: https://btor.fr
twitter_username: biiitor
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/biiitor
  - name: instagram
    url: https://www.instagram.com/btor.fr/
  - name: linkedin
    url: https://www.linkedin.com/in/thibaut-bayer//
  - name: github
    url: https://github.com/bt0r
  - name: twitch
    url: https://twitch.tv/bt0r
  - name: rss
    url: https://btor.fr/feed.xml

# Contact settings
contact_img: /assets/images/logo/logo.dark.small.png
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: btor.fr

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Thibaut BAYER
    bio: Passionné d'informatique, de développement web & applicatif depuis plus de 10 ans. Je partage mon quotidien de tech !
    url: http://btor.fr

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: true
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'btor'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
  - Makefile
  - docker-compose.yml
