version: "3"
services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    volumes:
      - ./:/srv/jekyll:delegated
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
    command: jekyll serve --watch --force_polling
