services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    volumes:
      - ./:/srv/jekyll:delegated
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"
    command: jekyll serve --open-url --livereload
