services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    volumes:
      - ./:/srv/jekyll:delegated
      - ./vendor/bundle:/usr/local/bundle
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1001
      TZ: Europe/Paris
    ports:
      - "4000:4000"
      - "35729:35729"
    command: jekyll serve --open-url --livereload
